from __future__ import annotations

import argparse
import csv
import hashlib
import json
from datetime import datetime
from pathlib import Path


H5AD_FILES = {
    "DLPFC": ("adata_auto_corr_DLPFC_1.h5ad", "adata_2_DLPFC.h5ad"),
    "MF": ("adata_MF_1.h5ad", "adata_MF_2.h5ad"),
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def record(path: Path, *, dataset: str, kind: str, display_path: str) -> dict[str, object]:
    return {
        "dataset": dataset,
        "kind": kind,
        "path": display_path,
        "bytes": path.stat().st_size,
        "modified": datetime.fromtimestamp(path.stat().st_mtime).astimezone().isoformat(timespec="seconds"),
        "sha256": sha256(path),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Record FigureS3 precomputed h5ad and panel provenance.")
    parser.add_argument("--data-root", type=Path, required=True)
    parser.add_argument("--panel-source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    rows: list[dict[str, object]] = []
    verified = {}
    for dataset, filenames in H5AD_FILES.items():
        h5ad_paths = [args.data_root / filename for filename in filenames]
        panel_paths = sorted((args.panel_source / dataset).glob("*.svg"))
        if len(panel_paths) != 12:
            raise ValueError(f"Expected 12 cached SVG panels for {dataset}, found {len(panel_paths)}")
        for path in h5ad_paths:
            rows.append(record(path, dataset=dataset, kind="precomputed_h5ad", display_path=path.name))
        for path in panel_paths:
            rows.append(
                record(
                    path,
                    dataset=dataset,
                    kind="cached_script_panel",
                    display_path=f"individual_panels/{dataset}/{path.name}",
                )
            )
        newest_input = max(path.stat().st_mtime for path in h5ad_paths)
        oldest_panel = min(path.stat().st_mtime for path in panel_paths)
        verified[dataset] = {
            "panel_count": len(panel_paths),
            "all_panels_newer_than_inputs": oldest_panel > newest_input,
        }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["dataset", "kind", "path", "bytes", "modified", "sha256"],
        )
        writer.writeheader()
        writer.writerows(rows)
    args.output.with_suffix(".json").write_text(
        json.dumps(
            {
                "source_policy": "Existing panels generated by the bundled Python plotting code; no spatial autocorrelation recalculation.",
                "datasets": verified,
                "records": len(rows),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    if not all(item["all_panels_newer_than_inputs"] for item in verified.values()):
        raise RuntimeError("At least one cached panel predates its h5ad input")
    print(json.dumps(verified, indent=2))


if __name__ == "__main__":
    main()
